name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/
  equatable: ^2.0.3
  flutter_sdeng_api:
    path: ../../api
  supabase_flutter: ^2.5.0


dev_dependencies:
  mocktail: ^1.0.2
  test: ^1.21.4
  very_good_analysis: ^5.1.0
