// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCseUSah8kgOXClqSVoL-9lSCXDXrVS5tI',
    appId: '1:386799374003:android:3b8aebaabed91fa19daac6',
    messagingSenderId: '386799374003',
    projectId: 'sdeng-84fe4',
    storageBucket: 'sdeng-84fe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3TpUHqsrMWSpPqWD1_BdRzveg9yboPfM',
    appId: '1:386799374003:ios:7a442586d18c70c09daac6',
    messagingSenderId: '386799374003',
    projectId: 'sdeng-84fe4',
    storageBucket: 'sdeng-84fe4.appspot.com',
    androidClientId: '386799374003-hj15ao1oa44agmav00cenu871c4dhs70.apps.googleusercontent.com',
    iosClientId: '386799374003-hu43kk9t6otd4si48tj92fudr7vtoea7.apps.googleusercontent.com',
    iosBundleId: 'com.teoromens.sdeng',
  );
}
